# Dependencies
markdown:         redcarpet
pygments:         true

# Server
exclude:          [".gitignore", ".ruby-version", "Gemfile", "Gemfile.lock"]
port:             4000

name: Wasim Akram
safe: true
lsi: false
url: "wasimakram.github.io"

twitter: _wasim
github: wasimakram

#Analytics
analytics :
  provider : google
  google : 
      tracking_id : 'UA-28692547-1'
